version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./backend/.env
    volumes:
      - /app/node_modules
      - ./backend:/app
  client:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
